// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnwlemsgxisocyewvnxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ud2xlbXNneGlzb2N5ZXd2bnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjM0NzQsImV4cCI6MjA2Njk5OTQ3NH0.kUAjrgCFac2rQgGTlwrlOixdRPo57pTmbsWsRMJrHY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});